### ISSUE TITLE
Dataset help

### ISSUE THREAD

**Issue by FeifanFu** [zhuduowang/ChangeViT#2]
Hello, can you provide the DSIFN-CD data collection divided into 256*256 compressed files?

**Comment by zhuduowang** [comment]
Sorry, we don't conduct experiments on DSIFN-CD. I can give you some instructions: (1) Download the [DSIFN-CD dataset](https://github.com/GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images/tree/master/dataset). (2) Use this [script](https://github.com/wgcban/ChangeFormer/blob/afd1b7ed640aa265a2c730de958416ae7356a2f9/data_preparation/dsifn_cd_256.m) to process the raw data.
